name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  install:
    name: Checkout & Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Node dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Persist workspace
        uses: actions/upload-artifact@v2
        with:
          name: wrkspc
          path: ${{ env.GITHUB_WORKSPACE }}
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Hydrate workspace
        uses: actions/download-artifact@v2
      - name: Lint
        run: |
          yarn format
          yarn lint
      - name: Test
        run: yarn test
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Hydrate workspace
        uses: actions/download-artifact@v2
      - name: Test
        run: yarn test
